import * as data from './data/data'
import * as kana from './data/kana'
import { parse } from './parse'

const getAllData = () => [
  data.DATA0,
  data.DATA1,
  data.DATA2,
  data.DATA3,
  data.DATA4,
  data.DATA5,
  data.DATA6,
  data.DATA7,
  data.DATA8,
  data.DATA9,
  data.DATA10,
  data.DATA11,
  data.DATA12,
  data.DATA13,
  data.DATA14,
  data.DATA15,
  data.DATA16,
  data.DATA17,
  data.DATA18,
  data.DATA19,
  data.DATA20,
  data.DATA21,
  data.DATA22,
  data.DATA23,
  data.DATA24,
  data.DATA25,
  data.DATA26,
  data.DATA27,
  data.DATA28,
  data.DATA29,
  data.DATA30,
  data.DATA31,
  data.DATA32,
  data.DATA33,
  data.DATA34,
  data.DATA35,
  data.DATA36,
  data.DATA37,
  data.DATA38,
  data.DATA39,
  data.DATA40,
  data.DATA41,
  data.DATA42,
  data.DATA43,
  data.DATA44,
  data.DATA45,
  data.DATA46
]

export const parseAll = () => getAllData().flatMap(data => parse(data))

export const parseAllWithKana = () => {
  const allData = getAllData()
  const allKana = [
    kana.KANA0,
    kana.KANA1,
    kana.KANA2,
    kana.KANA3,
    kana.KANA4,
    kana.KANA5,
    kana.KANA6,
    kana.KANA7,
    kana.KANA8,
    kana.KANA9,
    kana.KANA10,
    kana.KANA11,
    kana.KANA12,
    kana.KANA13,
    kana.KANA14,
    kana.KANA15,
    kana.KANA16,
    kana.KANA17,
    kana.KANA18,
    kana.KANA19,
    kana.KANA20,
    kana.KANA21,
    kana.KANA22,
    kana.KANA23,
    kana.KANA24,
    kana.KANA25,
    kana.KANA26,
    kana.KANA27,
    kana.KANA28,
    kana.KANA29,
    kana.KANA30,
    kana.KANA31,
    kana.KANA32,
    kana.KANA33,
    kana.KANA34,
    kana.KANA35,
    kana.KANA36,
    kana.KANA37,
    kana.KANA38,
    kana.KANA39,
    kana.KANA40,
    kana.KANA41,
    kana.KANA42,
    kana.KANA43,
    kana.KANA44,
    kana.KANA45,
    kana.KANA46
  ]

  return [...Array(allData.length)].flatMap((_, i) => parse(allData[i], allKana[i] as any))
}
