type Branded<T, U extends string> = T & { [key in U]: never }

type Pref0 = Branded<string, '_0'>
type Pref1 = Branded<string, '_1'>
type Pref2 = Branded<string, '_2'>
type Pref3 = Branded<string, '_3'>
type Pref4 = Branded<string, '_4'>
type Pref5 = Branded<string, '_5'>
type Pref6 = Branded<string, '_6'>
type Pref7 = Branded<string, '_7'>
type Pref8 = Branded<string, '_8'>
type Pref9 = Branded<string, '_9'>
type Pref10 = Branded<string, '_10'>
type Pref11 = Branded<string, '_11'>
type Pref12 = Branded<string, '_12'>
type Pref13 = Branded<string, '_13'>
type Pref14 = Branded<string, '_14'>
type Pref15 = Branded<string, '_15'>
type Pref16 = Branded<string, '_16'>
type Pref17 = Branded<string, '_17'>
type Pref18 = Branded<string, '_18'>
type Pref19 = Branded<string, '_19'>
type Pref20 = Branded<string, '_20'>
type Pref21 = Branded<string, '_21'>
type Pref22 = Branded<string, '_22'>
type Pref23 = Branded<string, '_23'>
type Pref24 = Branded<string, '_24'>
type Pref25 = Branded<string, '_25'>
type Pref26 = Branded<string, '_26'>
type Pref27 = Branded<string, '_27'>
type Pref28 = Branded<string, '_28'>
type Pref29 = Branded<string, '_29'>
type Pref30 = Branded<string, '_30'>
type Pref31 = Branded<string, '_31'>
type Pref32 = Branded<string, '_32'>
type Pref33 = Branded<string, '_33'>
type Pref34 = Branded<string, '_34'>
type Pref35 = Branded<string, '_35'>
type Pref36 = Branded<string, '_36'>
type Pref37 = Branded<string, '_37'>
type Pref38 = Branded<string, '_38'>
type Pref39 = Branded<string, '_39'>
type Pref40 = Branded<string, '_40'>
type Pref41 = Branded<string, '_41'>
type Pref42 = Branded<string, '_42'>
type Pref43 = Branded<string, '_43'>
type Pref44 = Branded<string, '_44'>
type Pref45 = Branded<string, '_45'>
type Pref46 = Branded<string, '_46'>

export type DataRow = { code: string; pref: string; city: string }
export type TownData = { town: string }
export type KanaRow = { prefKana: string; cityKana: string }
export type TownKana = { townKana: string }

export type Data = Branded<string, '_Data'>
export type Data0 = Data & Pref0
export type Data1 = Data & Pref1
export type Data2 = Data & Pref2
export type Data3 = Data & Pref3
export type Data4 = Data & Pref4
export type Data5 = Data & Pref5
export type Data6 = Data & Pref6
export type Data7 = Data & Pref7
export type Data8 = Data & Pref8
export type Data9 = Data & Pref9
export type Data10 = Data & Pref10
export type Data11 = Data & Pref11
export type Data12 = Data & Pref12
export type Data13 = Data & Pref13
export type Data14 = Data & Pref14
export type Data15 = Data & Pref15
export type Data16 = Data & Pref16
export type Data17 = Data & Pref17
export type Data18 = Data & Pref18
export type Data19 = Data & Pref19
export type Data20 = Data & Pref20
export type Data21 = Data & Pref21
export type Data22 = Data & Pref22
export type Data23 = Data & Pref23
export type Data24 = Data & Pref24
export type Data25 = Data & Pref25
export type Data26 = Data & Pref26
export type Data27 = Data & Pref27
export type Data28 = Data & Pref28
export type Data29 = Data & Pref29
export type Data30 = Data & Pref30
export type Data31 = Data & Pref31
export type Data32 = Data & Pref32
export type Data33 = Data & Pref33
export type Data34 = Data & Pref34
export type Data35 = Data & Pref35
export type Data36 = Data & Pref36
export type Data37 = Data & Pref37
export type Data38 = Data & Pref38
export type Data39 = Data & Pref39
export type Data40 = Data & Pref40
export type Data41 = Data & Pref41
export type Data42 = Data & Pref42
export type Data43 = Data & Pref43
export type Data44 = Data & Pref44
export type Data45 = Data & Pref45
export type Data46 = Data & Pref46

export type Kana = Branded<string, '_Kana'>
export type Kana0 = Kana & Pref0
export type Kana1 = Kana & Pref1
export type Kana2 = Kana & Pref2
export type Kana3 = Kana & Pref3
export type Kana4 = Kana & Pref4
export type Kana5 = Kana & Pref5
export type Kana6 = Kana & Pref6
export type Kana7 = Kana & Pref7
export type Kana8 = Kana & Pref8
export type Kana9 = Kana & Pref9
export type Kana10 = Kana & Pref10
export type Kana11 = Kana & Pref11
export type Kana12 = Kana & Pref12
export type Kana13 = Kana & Pref13
export type Kana14 = Kana & Pref14
export type Kana15 = Kana & Pref15
export type Kana16 = Kana & Pref16
export type Kana17 = Kana & Pref17
export type Kana18 = Kana & Pref18
export type Kana19 = Kana & Pref19
export type Kana20 = Kana & Pref20
export type Kana21 = Kana & Pref21
export type Kana22 = Kana & Pref22
export type Kana23 = Kana & Pref23
export type Kana24 = Kana & Pref24
export type Kana25 = Kana & Pref25
export type Kana26 = Kana & Pref26
export type Kana27 = Kana & Pref27
export type Kana28 = Kana & Pref28
export type Kana29 = Kana & Pref29
export type Kana30 = Kana & Pref30
export type Kana31 = Kana & Pref31
export type Kana32 = Kana & Pref32
export type Kana33 = Kana & Pref33
export type Kana34 = Kana & Pref34
export type Kana35 = Kana & Pref35
export type Kana36 = Kana & Pref36
export type Kana37 = Kana & Pref37
export type Kana38 = Kana & Pref38
export type Kana39 = Kana & Pref39
export type Kana40 = Kana & Pref40
export type Kana41 = Kana & Pref41
export type Kana42 = Kana & Pref42
export type Kana43 = Kana & Pref43
export type Kana44 = Kana & Pref44
export type Kana45 = Kana & Pref45
export type Kana46 = Kana & Pref46

type Word = { kana: string; kanji: string }
export type Row = { code: string; address: [Word, Word, Word | null] }
